### ISSUE TITLE
Discuss organization of code

### ISSUE THREAD

**Issue by jstonge** [jstonge/allotaxonometer#20]
Typology of accessibility for the ALLotaxonometer project:

  1. We offer a user-friendly web application where users can effortlessly generate an allotaxonograph by simply dragging and dropping a properly formatted data file, eliminating the need for installation. 
  2. To bring allotaxonometer to Python users
  3. Users familiar with Svelte for creating interactive tutorials.

Right now, we have the 2 following libraries

 - [allotaxonometer](https://github.com/jstonge/allotaxonometer). This repo. 
   - This is a [npm](https://www.npmjs.com/package/allotaxonometer) package 
   - Serves as current "backend" of the project, aka we make the calculation for the allotaxonometry.
      - utilities to combine the two systems of interests into a single object
      - calculate different divergence metrics
   - We also have individual charting components in `d3js`, which can be combined elsewhere (e.g.`py-allotax`).
 - [py-allotax](https://github.com/carterwward/py-allotax/). Python library.
   - deps on `allotaxonometer.js`
   - We use python `subprocess` module, with [jsdom](https://github.com/jsdom/jsdom), to run `allotaxonometer.js`.
   - We intercept the output in python (still TBD how to best do it)

We also have [allotaxp](https://github.com/jstonge/allotaxp), which is a toy project for svelte users. 
   - It is the code for the web app that lives [here](https://allotaxp.vercel.app/)
   - It is written in svelte+d3
   - It depends on `allotaxonometer.js` for wrangling the data that is provided by the users. But not the charting code that is in allotaxonometer.
   - It is in the process to be rewritten in svelte 5, when JSO finds time.

**Comment by jstonge** [comment]
> I think keeping it separated is fine. I am wondering how we can make sure, if it all, that updates to the main backend repo are pushed to all functionality. E.g., if someone adds the density lines. Can be part of the organization thought process. Do we _need_ to be concerned about updates? Is this tool finished after this anyway?

Allotaxonometer is never finished 😂. I mean, there were many plans to add interactivity to it. It would be nice if all the updates to the main backend repo spread to the rest. Maybe we could make the web page app in observable framework,  using the same code from the main backend repo. It should be doable. The only thing that is unclear to me is how to create a button to download PDF in observable framework, but this is surely doable.

But the Svelte code is just different than the rest. I might just keep that as my pet project. I like the possibility to do more funky stuff that is only doable in Svelte (like the scrollytelling, or I dunnow. The sky is the limit).

**Comment by amafehr** [comment]
Good discussion. Will include the draw.io in the py-allotax repo as a living document but am attaching the current organization of allotax tools here. 
![allo_diagram0 1](https://github.com/user-attachments/assets/2009fe35-3f31-4614-afb4-943f01eee715)

**Comment by jstonge** [comment]
@amafehr One thing I am still dubious is whether it is weird to write charting code for `py-allotax` in `allotaxonometer.js`. At the end of the day, the plots in `allotaxonometer.js` will only work for `py-allotax`. I am wondering if we should move that js code into `py-allotax`, even if it means `py-allotax` will have more javascript code as a result.

**Comment by amafehr** [comment]
I still like your idea of making a branch in the main `allotaxonometer` repo and `npm install` that branch. A pro is that we can still pull relevant changes (pick and apply without breaking) from main into py-allotax's branch. Then the main allotax repo is still left alone, truly serving as a base for extensibility.

**Comment by amafehr** [comment]
Or perhaps we get 1 version with the needed changes in npm, then re-publish the main library? So 1.1.13 would just be for py-all ok tax. Not sure. Thoughts?

**Comment by amafehr** [comment]
Update of ecosystem
![allo_diagram](https://github.com/user-attachments/assets/77b76567-adee-4b12-9ba7-8d51796b45d7)

**Comment by amafehr** [comment]
I think we can close this @jstonge.
